document.addEventListener("DOMContentLoaded",()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const menu=$(".menu"),nav=$(".nav-links");menu?.addEventListener("click",()=>nav?.classList.toggle("open"));$$(".nav-links a").forEach(a=>a.addEventListener("click",()=>nav?.classList.remove("open")));
$$("[data-filter]").forEach(btn=>btn.addEventListener("click",()=>{const f=btn.dataset.filter;$$("[data-filter]").forEach(b=>b.classList.toggle("active",b===btn));$$(".project").forEach(p=>p.classList.toggle("hide",f!=="all"&&p.dataset.category!==f));}));
$$("[data-modal]").forEach(btn=>btn.addEventListener("click",()=>$("#"+btn.dataset.modal)?.classList.add("open")));$$(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open")}));
$$(".accordion button").forEach(b=>b.addEventListener("click",()=>{const p=b.nextElementSibling;p.style.maxHeight=p.style.maxHeight?null:p.scrollHeight+"px"}));
const range=$("[data-scope-range]");if(range){const out=$("[data-scope-output]"),days=$("[data-scope-days]"),bar=$("[data-scope-bar]");const calc=()=>{const v=+range.value;out.textContent="$"+(Math.round(v*1850/1000)*1000).toLocaleString();days.textContent=Math.round(28+v*.72)+" days";bar.style.width=Math.min(96,20+v*.76)+"%"};range.addEventListener("input",calc);calc()}
const complexity=$("[data-complexity]"),price=$("[data-price]");complexity?.addEventListener("change",()=>price.textContent="$"+({single:4200,standard:18500,enterprise:62000}[complexity.value]||0).toLocaleString());
$$(".dropzone").forEach(z=>{const input=$("input[type=file]",z);z.addEventListener("click",()=>input?.click());input?.addEventListener("change",()=>{const list=z.parentElement.querySelector(".file-list");if(!list)return;[...input.files].forEach(f=>{const row=document.createElement("div");row.className="file-row";row.innerHTML="<strong>"+f.name+"</strong><div class='file-progress'><span></span></div><small>Uploading</small>";list.append(row);setTimeout(()=>{row.querySelector("span").style.width="100%";row.querySelector("small").textContent="Ready"},700)})})});
const form=$(".smart-form");form?.addEventListener("submit",e=>{e.preventDefault();let ok=true;$$("[required]",form).forEach(i=>{const er=i.parentElement.querySelector(".error");if(!i.value.trim()){ok=false;if(er)er.textContent="This field is required."}else if(er)er.textContent=""});if(ok)$("[data-form-message]",form).textContent="Transmission validated. Your enquiry is ready for routing."});
const canvas=$("#waterfall");if(canvas){const ctx=canvas.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2);let t=0;function resize(){canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}function draw(){t+=.012;ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<22;i++){ctx.beginPath();for(let x=0;x<=innerWidth;x+=14){const y=innerHeight*.2+i*innerHeight*.045+Math.sin(x*.006+t+i)*30+Math.sin(x*.013-t*1.5)*18;ctx.lineTo(x,y)}ctx.strokeStyle="hsla("+(20+i*5)+",90%,58%,"+(.035+i*.004)+")";ctx.lineWidth=28;ctx.stroke()}requestAnimationFrame(draw)}addEventListener("resize",resize);resize();draw()}
});