document.addEventListener("DOMContentLoaded",()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const menu=$(".menu"),nav=$(".nav-links");menu?.addEventListener("click",()=>nav?.classList.toggle("open"));$$(".nav-links a").forEach(a=>a.addEventListener("click",()=>nav?.classList.remove("open")));
$$("[data-filter]").forEach(btn=>btn.addEventListener("click",()=>{const f=btn.dataset.filter;$$("[data-filter]").forEach(b=>b.classList.toggle("active",b===btn));$$(".project").forEach(p=>p.classList.toggle("hide",f!=="all"&&p.dataset.category!==f));}));
$$("[data-modal]").forEach(btn=>btn.addEventListener("click",()=>$("#"+btn.dataset.modal)?.classList.add("open")));$$(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open")}));
$$(".accordion button").forEach(b=>b.addEventListener("click",()=>{const p=b.nextElementSibling;p.style.maxHeight=p.style.maxHeight?null:p.scrollHeight+"px"}));
const range=$("[data-scope-range]");if(range){const out=$("[data-scope-output]"),days=$("[data-scope-days]"),bar=$("[data-scope-bar]");const calc=()=>{const v=+range.value;out.textContent="$"+(Math.round(v*1850/1000)*1000).toLocaleString();days.textContent=Math.round(28+v*.72)+" days";bar.style.width=Math.min(96,20+v*.76)+"%"};range.addEventListener("input",calc);calc()}
const complexity=$("[data-complexity]"),price=$("[data-price]");complexity?.addEventListener("change",()=>price.textContent="$"+({single:4200,standard:18500,enterprise:62000}[complexity.value]||0).toLocaleString());
const form=$(".smart-form");form?.addEventListener("submit",e=>{e.preventDefault();let ok=true;$$("[required]",form).forEach(i=>{const er=i.parentElement.querySelector(".error");if(!i.value.trim()){ok=false;if(er)er.textContent="This field is required."}else if(er)er.textContent=""});if(ok)$("[data-form-message]",form).textContent="Transmission validated. Your enquiry is ready for routing."});
const canvas=$("#waterfall");if(canvas){const ctx=canvas.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2);let t=0;function resize(){canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}function draw(){t+=.012;ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<22;i++){ctx.beginPath();for(let x=0;x<=innerWidth;x+=14){const y=innerHeight*.2+i*innerHeight*.045+Math.sin(x*.006+t+i)*30+Math.sin(x*.013-t*1.5)*18;ctx.lineTo(x,y)}ctx.strokeStyle="hsla("+(20+i*5)+",90%,58%,"+(.035+i*.004)+")";ctx.lineWidth=28;ctx.stroke()}requestAnimationFrame(draw)}addEventListener("resize",resize);resize();draw()}

// Extended page interactions
$('[data-person]').forEach(b=>b.addEventListener('click',()=>{const parts=b.dataset.person.split('|');const modal=$('#profile-modal');if(modal){$('[data-person-title]',modal).textContent=parts[0];$('[data-person-role]',modal).textContent=parts[1];$('[data-person-copy]',modal).textContent=parts[2];modal.classList.add('open')}}));
$('[data-compliance]').forEach(b=>b.addEventListener('click',()=>{const parts=b.dataset.compliance.split('|');const modal=$('#compliance-modal');if(modal){$('[data-compliance-title]',modal).textContent=parts[0];$('[data-compliance-copy]',modal).textContent=parts[1];modal.classList.add('open')}}));
$('[data-service]').forEach(b=>b.addEventListener('click',()=>{const parts=b.dataset.service.split('|');const modal=$('#service-modal');if(modal){$('[data-service-title]',modal).textContent=parts[0];$('[data-service-copy]',modal).textContent=parts[1];modal.classList.add('open')}}));
$('[data-client-phase]').forEach(b=>b.addEventListener('click',()=>{const parts=b.dataset.clientPhase.split('|');const modal=$('#client-phase-modal');if(modal){$('[data-client-phase-title]',modal).textContent=parts[0];$('[data-client-phase-copy]',modal).textContent=parts[1];modal.classList.add('open')}}));
$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>b.closest('.modal')?.classList.remove('open')));
$('[data-toast]').forEach(b=>b.addEventListener('click',()=>{const box=$('[data-toast-box]');if(!box)return;box.textContent=b.dataset.toast;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),2400)}));
const area=$('[data-area-range]');if(area){const out=$('[data-area-output]'),complexity=$('[data-complexity]'),price=$('[data-price]');const sync=()=>{out.textContent=area.value+' / 10';const base={single:4200,standard:18500,enterprise:62000}[complexity?.value||'standard']||18500;price.textContent='+Math.round(base*(.72+area.value*.056)).toLocaleString()};area.addEventListener('input',sync);complexity?.addEventListener('change',sync);sync()}
});